default_context:
  project_name: 'FacScience'
  project_slug: 'FacScience'
  domain_main: 'facscience.com'
  domain_staging: 'stag.facscience.com'
  docker_swarm_stack_name_main: 'facscience-com'
  docker_swarm_stack_name_staging: 'stag-facscience-com'
  secret_key: 'qs4d68a1q3s4dq4a31a8qd13e51aeta1dae4tz11gsd8g4ze5zgs1gd1g1zzg1543rjr3'
  first_superuser: 'admin@science.com'
  first_superuser_password: 'aze135azq35sfsnf6353sfh3xb68yyp31gf68k5sf6h3s5d68jd5'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.science.com", "https://stag.science.com", "https://science.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'facscience@gmail.com'
  postgres_password: 'qsd46q3c1v3t3jt3uo3fg34d6hzrz5r135dfh35uerfh632zzry1hzr4z'
  pgadmin_default_user: 'admin@science.com'
  pgadmin_default_user_password: 'aze135azq35sfsnf6353sfh3xb68yyp31gf68k5sf6h3s5d68jd5'
  traefik_constraint_tag: 'facscience.com'
  traefik_constraint_tag_staging: 'stag.facscience.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:aze135azq35sfsnf6353sfh3xb68yyp31gf68k5sf6h3s5d68jd5'
  sentry_dsn: ''
  docker_image_prefix: 'science'
  docker_image_backend: 'backendscience'
  docker_image_celeryworker: 'celeryworkerscience'
  docker_image_frontend: 'frontendscience'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
