from sqlalchemy.sql.operators import is_natural_self_precedent
from .item import Item
from .user import User
from .mention import Mention
from .role import Role
from .parcours import Parcours
from .semestre import Semestre
from .anne_univ import AnneUniv
from .semestre_valide import SemestreValide
from .etudiant import create
from .test import create_table
